bet365Project/bet365/urls.py
from django.urls import path
from .views import bet365_view, bets, post

app_name= 'bet365'

urlpatterns = [
    path('', bet365_view, name = "home"),
    path("bets/", bets, name = "allBets"),
    path('bets/<int:id>/', post, name= 'post')

]

bet365Project/home/urls.py
from django.urls import path
from .views import home_view


app_name = 'home'
urlpatterns = [
    path("", home_view, name= "index")
]

bet365Project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from bet365.views import bet365_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bet365/", include('bet365.urls')),
    path("", include('home.urls')),
]

bet365Project/bet365/models.py
from django.db import models

# Create your models here.

bet365Project/home/models.py
from django.db import models

# Create your models here.

bet365Project/bet365/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, Http404
from bet365.data import posts
from typing import Any

def bet365_view(request: HttpRequest) -> HttpResponse:
    context = {
        "text": "Aqui tem alguns insights sobre as bets feitas na casa de apostas da bet365",
        "title": "bet365 Home Page",
    }
    return render(request, "bet365/home.html", context=context)


def bets(request: HttpRequest) -> HttpResponse:
    context = {
        "text": "Aqui tem todas as bets já realizadas na bet365",
        "title": "bet365 All bets",
        "posts": posts,
    }
    return render(request, "bet365/bet365.html", context=context)


def post(request: HttpRequest, id: int) -> HttpResponse:
    found_post:dict[str, Any] | None= None
    post_id = 0
    for p in posts:
        if p["id"] == id:
            found_post = p
            post_id= p['id']
            break

    if found_post is None:
        raise Http404("Post não existe.")
    context = {
        "text": f"Bet de id {post_id}",
        "title": "- " +  found_post['title'],
        "post": found_post
    }
    return render(request, "bet365/bet365.html", context=context)

bet365Project/home/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest



# function based views
def home_view(request: HttpRequest) -> HttpResponse:
    context = {"text": "Página incial do projeto das bets porém feito com context. FODA!"}
    return render(
        request,
        "home/index.html",
        
        context=context,
    )

bet365Project/bet365/templates/bet365/bet365.html
{% extends "global/base.html" %}
{% block texto %}{{text}}{% endblock texto %}
{% block posts %} 
    {% if posts %}
        {% for post in posts %}
            {% include "global/partials/postblock.html" %}
        {% endfor %}
    {% elif post %}
        <article class="post single-post">
            <a href="{% url "bet365:post" post.id %}">
                <header>
                    <h2 class="post__title">
                        {{ post.title }}
                    </h2>
                </header>
                <div class="post__body">
                    {{post.body}}
                </div>
            </a>
        </article>
    {% endif %}

    
{% endblock posts %} 

bet365Project/bet365/templates/bet365/home.html
{% extends "global/base.html" %}
{% block texto %}{{text}}{% endblock texto %}
{% block posts %} {% include "global/partials/data.html" %}{% endblock posts %} 

bet365Project/home/templates/home/index.html
{% extends "global/base.html" %}
{% block texto %}{{text}}{% endblock texto %}
{% block posts %}{% include "global/partials/home.html" %}{% endblock posts %}